ECHO_UPPER = "ECHO_UPPER"
ECHO_CAPITALIZE = "ECHO_CAPITALIZE"

LANGUAGE_ENGLISH = "langEN"
LANGUAGE_ROUTER = "langRR"

TUTORIAL_FINISH = "TUTORIAL_FINISH"

RESTART_CONTINUE = "RESTART_CONTINUE" 
RESTART_CANCEL = "RESTART_CANCEL"

PREFERENCES_LANGUAGE = "PREFERENCES_LANGUAGE"
PREFERENCES_SECTIONS = "PREFERENCES_SECTIONS"
PREFERENCES_ENTRIES = "PREFERENCES_ENTRIES"
PREFERENCES_TIME = "PREFERENCES_TIME"

TOGGLE_SECTION_EVENTS = "toggleEvents =="
TOGGLE_SECTION_BIRTHS = "toggleBirths =="
TOGGLE_SECTION_DEATHS = "toggleDeaths =="
TOGGLE_SECTION_HOLIDAYS = "toggleHolidays and observances =="