ECHO_UPPER = "ECHO_UPPER"
ECHO_CAPITALIZE = "ECHO_CAPITALIZE"

LANGUAGE_ENGLISH = "langen"
LANGUAGE_ROUTER = "langRR"
LANGUAGE_UKRAINIAN = "languk"

TUTORIAL_FINISH = "TUTORIAL_FINISH"

RESTART_CONTINUE = "RESTART_CONTINUE" 
RESTART_CANCEL = "RESTART_CANCEL"

PREFERENCES_MAIN = "PREFERENCES_MAIN"
PREFERENCES_LANGUAGE = "PREFERENCES_LANGUAGE"
PREFERENCES_SECTIONS = "PREFERENCES_SECTIONS"
PREFERENCES_ENTRIES = "PREFERENCES_ENTRIES"
PREFERENCES_TIME = "PREFERENCES_TIME"

TOGGLE_SECTION_EVENTS = "toggleEvents"
TOGGLE_SECTION_BIRTHS = "toggleBirths"
TOGGLE_SECTION_DEATHS = "toggleDeaths"
TOGGLE_SECTION_HOLIDAYS = "toggleHolidays and observances"

INPUT_ENTRIES_PRE1600 = "input0"
INPUT_ENTRIES_1601_1900 = "input1"
INPUT_ENTRIES_MODERN = "input2"
INPUT_ENTRIES_HOLIDAYS = "input3"