import json

import DataManager

ERR_SOMETHING_WRONG = "ERR_SOMETHING_WRONG"
ERR_COMMAND_NOT_EXIST = "ERR_COMMAND_NOT_EXIST"
ERR_NOT_TEXT_INPUT = "ERR_NOT_TEXT_INPUT"
ERR_INVALID_DATE = "ERR_INVALID_DATE"
ERR_INVALID_FORMAT = "ERR_INVALID_FORMAT"
ERR_UNFINISHED_INPUT = "ERR_UNFINISHED_INPUT"
ERR_WIKI_LIMIT = "ERR_WIKI_LIMIT"
ERR_USER_PENDING = "ERR_USER_PENDING"

BUT_ECHO_UPPER = "BUT_ECHO_UPPER"
BUT_ECHO_CAPITALIZE = "BUT_ECHO_CAPITALIZE"
BUT_TUTOR_FINISH = "BUT_TUTOR_FINISH"
BUT_RESTART_CONTINUE = "BUT_RESTART_CONTINUE"
BUT_RESTART_CANCEL = "BUT_RESTART_CANCEL"
BUT_SECTION_EVENTS = "BUT_SECTION_EVENTS"
BUT_SECTION_BIRTHS = "BUT_SECTION_BIRTHS"
BUT_SECTION_DEATHS = "BUT_SECTION_DEATHS"
BUT_SECTION_HOLIDAYS = "BUT_SECTION_HOLIDAYS"
BUT_ENTRIES_PRE1600 = "BUT_ENTRIES_PRE1600"
BUT_ENTRIES_1601_1900 = "BUT_ENTRIES_1601_1900"
BUT_ENTRIES_MODERN = "BUT_ENTRIES_MODERN"
BUT_ENTRIES_HOLIDAYS = "BUT_ENTRIES_HOLIDAYS"
BUT_PREFERENCES_GO_BACK = "BUT_PREFERENCES_GO_BACK"
BUT_INPUT_CANCEL = "BUT_INPUT_CANCEL"

COM_START = "COM_START"
COM_HELP = "COM_HELP"
COM_EVENTSTODAY = "COM_EVENTSTODAY"
COM_EVENTSTHATDAY = "COM_EVENTSTHATDAY"
COM_EVENTSTHATDAY_ALL = "COM_EVENTSTHATDAY_ALL"
COM_PREFERENCES = "COM_PREFERENCES"
COM_LANGUAGE = "COM_LANGUAGE"
COM_SECTIONS = "COM_SECTIONS"
COM_ENTRIES = "COM_ENTRIES"
COM_SCHEDULE = "COM_SCHEDULE"

INF_HELP_HEADER = "INF_HELP_HEADER"
INF_TUTOR_NOTICE = "INF_TUTOR_NOTICE"
INF_PREFERENCES = "INF_PREFERENCES"
INF_SELECT_DATE = "INF_SELECT_DATE"
INF_SECTIONS = "INF_SECTIONS"
INF_ENTRIES = "INF_ENTRIES"
INF_ENTRIES_INPUT = "INF_ENTRIES_INPUT"
INF_TIME_INPUT = "INF_TIME_INPUT"
INF_KYIV_TIME = "INF_KYIV_TIME"

INF_SOURCE = "INF_SOURCE"
INF_EVENTS = "INF_EVENTS"
INF_BIRTHS = "INF_BIRTHS"
INF_DEATHS = "INF_DEATHS"
INF_HOLIDAYS = "INF_HOLIDAYS"

PRO_RESTART = "PRO_RESTART"

PRF_LANGUAGE = "PRF_LANGUAGE" 
PRF_SECTIONS = "PRF_SECTIONS"
PRF_ENTRIES = "PRF_ENTRIES"
PRF_TIME = "PRF_TIME"
PRF_SECTION_EVENTS = "PRF_SECTION_EVENTS" 
PRF_SECTION_BIRTHS = "PRF_SECTION_BIRTHS" 
PRF_SECTION_DEATHS = "PRF_SECTION_DEATHS" 
PRF_SECTION_HOLIDAYS = "PRF_SECTION_HOLIDAYS"
PRF_ENTRIES_PRE1600 = "PRF_ENTRIES_PRE1600"
PRF_ENTRIES_1601_1900 = "PRF_ENTRIES_1601_1900" 
PRF_ENTRIES_MODERN = "PRF_ENTRIES_MODERN"


selectedLocale = "EN"
locales = {}
with open("./locales.json", encoding="UTF-8") as localeFile:
    locales = json.load(localeFile)


def getStringDirectly(stringName, userId:int):
    language = DataManager.getValue("lang", str(userId))
    return locales[language].get(stringName, "?")

def setLocale(lang):
    global selectedLocale
    selectedLocale = lang

def setLocaleById(userId:int):
    setLocale(DataManager.getValue("lang", str(userId)))

def get(stringName):
    return locales[selectedLocale].get(stringName, "?")