import json

import DataManager

ERR_SOMETHING_WRONG = "ERR_SOMETHING_WRONG"
ERR_COMMAND_NOT_EXIST = "ERR_COMMAND_NOT_EXIST"
ERR_NOT_TEXT_INPUT = "ERR_NOT_TEXT_INPUT"
ERR_INVALID_DATE = "ERR_INVALID_DATE"

BUT_ECHO_UPPER = "BUT_ECHO_UPPER"
BUT_ECHO_CAPITALIZE = "BUT_ECHO_CAPITALIZE"
BUT_TUTOR_FINISH = "BUT_TUTOR_FINISH"
BUT_RESTART_CONTINUE = "BUT_RESTART_CONTINUE"
BUT_RESTART_CANCEL = "BUT_RESTART_CANCEL"
BUT_SECTION_EVENTS = "BUT_SECTION_EVENTS"
BUT_SECTION_BIRTHS = "BUT_SECTION_BIRTHS"
BUT_SECTION_DEATHS = "BUT_SECTION_DEATHS"
BUT_SECTION_HOLIDAYS = "BUT_SECTION_HOLIDAYS"

COM_START = "COM_START"
COM_HELP = "COM_HELP"
COM_EVENTSTODAY = "COM_EVENTSTODAY"
COM_EVENTS_THAT_DAY = "COM_EVENTS_THAT_DAY"
COM_EVENTS_THAT_DAY_ALL = "COM_EVENTS_THAT_DAY_ALL"
COM_PREFERENCES = "COM_PREFERENCES"

INF_HELP_HEADER = "INF_HELP_HEADER"
INF_TUTOR_NOTICE = "INF_TUTOR_NOTICE"
INF_PREFERENCES = "INF_PREFERENCES"
INF_SELECT_DATE = "INF_SELECT_DATE"

PRO_RESTART = "PRO_RESTART"

PRF_LANGUAGE = "PRF_LANGUAGE" 
PRF_SECTIONS = "PRF_SECTIONS"
PRF_ENTRIES = "PRF_ENTRIES"
PRF_TIME = "PRF_TIME"
PRF_SECTION_EVENTS = "PRF_SECTION_EVENTS" 
PRF_SECTION_BIRTHS = "PRF_SECTION_BIRTHS" 
PRF_SECTION_DEATHS = "PRF_SECTION_DEATHS" 
PRF_SECTION_HOLIDAYS = "PRF_SECTION_HOLIDAYS"


selectedLocale = "EN"
locales = {}
with open("./locales.json") as localeFile:
    locales = json.load(localeFile)


def getStringDirectly(stringName, userId:int):
    language = DataManager.get("lang", str(userId))
    return locales[language].get(stringName, "?")

def setLocaleById(userId:int):
    global selectedLocale
    selectedLocale = DataManager.get("lang", str(userId))

def get(stringName):
    return locales[selectedLocale].get(stringName, "?")